Обновление для сборки с помощью docker.
rominf/latex-g7-32 pull request #118
Opened 2023-03-26 06:22 UTC by afaikiac

Спасибо большое за этот проект! Надеюсь мой PR сделает его чуть более удобным в использовании. Список того, что я изменил:

- обновил дистрибутив до Debian Bookworm. Debian Stretch уже устарел, и обновление позволит сократить время сборки контейнера, которое ранее занимало целую вечность из-за необходимости сборки пакетов;

- добавил возможность устанавливать файлы шрифтов из папки `fonts`;

- упростил процесс сборки, оставив только сборку с помощью Xelatex;

- исправил флаг для Inkscape и название стиля в библиографии, чтобы PDF собиралась без ошибок.

Прикрепляю пример собранной PDF: [rpz-cmake-xelatex.pdf](https://github.com/latex-g7-32/latex-g7-32/files/11070919/rpz-cmake-xelatex.pdf)

2023-03-26 07:13 UTC, einhander requested changes

2023-03-26 07:13 UTC, einhander commented on tex/81-biblio.tex
> +\bibliographystyle{gost780u}
Зачем ставить старый gost780, если берется ugost2008 из дистрибутива. В bookworm нужно класть ugost2008.bst с сайта разработчика, в texlive лежит старая версия, которая выдает ошибку. В остальных дистрибутивах LaTeX такой проблемы нет.

2023-03-26 10:48 UTC, afaikiac commented
[rpz-cmake-xelatex.pdf](https://github.com/latex-g7-32/latex-g7-32/files/11071364/rpz-cmake-xelatex.pdf)

2023-03-26 11:03 UTC, afaikiac commented
Не знаю хорошая ли это практика, брать bst файлы из репозитория. Если вы можете подсказать, в каком дистрибутиве актуальная версия, то я могу пересобрать докер с ней. Я выбирал так, чтобы был тех 22 года, и чтобы это был не роллинг дистрибутив.

2023-03-27 08:33 UTC, einhander commented
> Не знаю, хорошая ли это практика брать bst файлы из репозитория. Если вы можете подсказать, в каком дистрибутиве актуальная версия, то я могу пересобрать докер с ним. Я выбирал так, чтобы был тех 22 года и чтобы это был не роллинг дистрибутив.

 Чего только в докер не тянут)) Вот [тут](https://github.com/kia999/GOST/issues/23) описан патч, можешь его сделать, по сути убрать одну строку. Или взять сам файл с самого репозитория. Ctan версию нужно генерировать из dtx файла, ИМХО сложнее.

2023-03-27 10:13 UTC, afaikiac commented
> Чего только в докер не тянут)) Вот [тут](https://github.com/kia999/GOST/issues/23) описан патч, можешь его сделать, по сути убрать одну строку. Или взять сам файл с самого репозитория. Ctan версию нужно генерировать из dtx файла, ИМХО сложнее.

Сделал вариант с сабмодулем. И просто копирую bst файлы в корень проекта в cmake. Мне кажется это лучше, тк не надо тянуть сам файл, да и обновлять его проще. А если человек захочет сам как-то собрать проект, он может просто объявить `BSTINPUTS`. @einhander, что думаете?

2023-03-27 10:24 UTC, einhander commented
Да, думаю так все же лучше будет.

2023-03-27 10:25 UTC, einhander approved these changes

2023-03-27 10:26 UTC, einhander commented
@afaikiac все готово, можно мержить?

2023-03-27 10:29 UTC, afaikiac commented
> @afaikiac все готово, можно мержить?

Да, все проверил, работает [rpz-cmake-xelatex.pdf](https://github.com/latex-g7-32/latex-g7-32/files/11077514/rpz-cmake-xelatex.pdf)

2023-03-27 10:31 UTC, merged